### ISSUE TITLE
Unexpected NaN in add

### ISSUE THREAD

**Issue by Reinhardt-C** [Naruyoko/OmegaNum.js#22]
```javascript
OmegaNum.add(0, 1e16).toString();
"NaN"
```
I'm too lazy to fix it rn

**Comment by Naruyoko** [comment]
[α 1.0.2](https://github.com/Naruyoko/OmegaNum.js/commit/611fc266ed4587d879d52f7e9e54a78a300e610a)

**Comment by James103** [comment]
Expected result:
```
OmegaNum.add(0, 1e16).toString();
"1e16"
```
My testing from https://naruyoko.github.io/OmegaNum.js/index.html:
```
OmegaNum.add(0, 1e16).toString();
"1e16"
```
Result: This is accurate. 0 plus any number X should return that number X no matter how big/small it is.
