### ISSUE TITLE
The results is wrong

### ISSUE THREAD

**Issue by qq1010903229** [Naruyoko/OmegaNum.js#23]
In my calculation, [1,0,1] = 10^^1=10 and [1,0,0,1]=10^^^1=10

But OmegaNum([1,0,1]) -> 10000000000,  OmegaNum([1,0,0,1]) -> [10000000000,9]

What?

**Comment by Reinhardt-C** [comment]
Looks like something in standardization. I'll look into it. If necessary, just work around it.

**Comment by Naruyoko** [comment]
[α 1.0.2](https://github.com/Naruyoko/OmegaNum.js/commit/611fc266ed4587d879d52f7e9e54a78a300e610a)

**Comment by qq1010903229** [comment]
Thanks for the α 1.0.2 update. The bug is fixed.
