### ISSUE TITLE
Wrong number from string

### ISSUE THREAD

**Issue by Reinhardt-C** [Naruyoko/OmegaNum.js#25]
OmegaNum('10^^10') == OmegaNum('10') for some reason.

**Comment by Reinhardt-C** [comment]
In a kind of unrelated issue:
OmegaNum('10^^9') is what '10^^10' should be. Ugh, this breaks my brain.

**Comment by Naruyoko** [comment]
[α 1.0.2](https://github.com/Naruyoko/OmegaNum.js/commit/611fc266ed4587d879d52f7e9e54a78a300e610a)

**Comment by James103** [comment]
Just checked on https://naruyoko.github.io/OmegaNum.js/index.html:
```
OmegaNum('10^^10') == OmegaNum('10') 
false
OmegaNum('10^^10').toString()
(10^)^8 10000000000
OmegaNum('10^^9').toString()
eeeeeee10000000000
OmegaNum('10')
10
```
