### ISSUE TITLE
Wrong results from string.

### ISSUE THREAD

**Issue by qq1010903229** [Naruyoko/OmegaNum.js#26]
new OmegaNum("10^^100") == 1, not [100,0,1]
new OmegaNum("10^^101") == 10, not [101,0,1]
new OmegaNum("10^^1000") == 1, not [1000,0,1]
new OmegaNum("10^^1001") == 10, not [1001,0,1]
new OmegaNum("10^^10000") == 1, not [10000,0,1]

See #25 .
What?

**Comment by Reinhardt-C** [comment]
Yeah, this stuffed me up so bad when I was creating notations for my game. I couldn't figure out why my code was giving the wrong answer.

**Comment by Naruyoko** [comment]
[α 1.0.2.2](https://github.com/Naruyoko/OmegaNum.js/commit/adab2ca2ffb8420547a375bc8d6964588c9cc0c6)

**Comment by qq1010903229** [comment]
![image](https://user-images.githubusercontent.com/37618983/67142836-ba3c2c80-f297-11e9-8d85-142324f0c790.png)

**Comment by Naruyoko** [comment]
Fixed.
![10^^101](https://user-images.githubusercontent.com/32781397/67153233-7ce59800-f2b3-11e9-859d-1846dca321c0.PNG)

**Comment by Reinhardt-C** [comment]
YAY
