### ISSUE TITLE
Broken Clone Function (and therefore pretty much the entire library doesn't work)

### ISSUE THREAD

**Issue by Reinhardt-C** [Naruyoko/OmegaNum.js#27]
You used input1 instead of input in like 5 places

**Comment by Naruyoko** [comment]
[α 1.0.2.2](https://github.com/Naruyoko/OmegaNum.js/commit/adab2ca2ffb8420547a375bc8d6964588c9cc0c6)

**Comment by Reinhardt-C** [comment]
Wasn't my first issue but okay.
