### ISSUE TITLE
cmp is incorrect for negative numbers

### ISSUE THREAD

**Issue by Patashu** [Naruyoko/OmegaNum.js#3]
```
new OmegaNum(-1).cmp(new OmegaNum(-2))
-1
```

(should be 1 since -1 > -2)

to fix this, you just have to multiply the return value by the sign if the signs are different, e.g. https://github.com/Patashu/break_eternity.js/blob/master/break_eternity.js#L1456

**Comment by Naruyoko** [comment]
α 1.0.1

**Comment by Patashu** [comment]
Not fixed, now I get this instead:

```
new OmegaNum(-1).cmp(new OmegaNum(-2))
OmegaNum.html:129 Uncaught TypeError: this.neg(...).cmp(...).neg is not a function
    at OmegaNum.P.compareTo.P.cmp (OmegaNum.html:129)
    at <anonymous>:1:18
```

**Comment by Naruyoko** [comment]
*Facepalm* Of course it doesn't work, I'm `neg()`ing on a **Number**!

**Comment by Naruyoko** [comment]
[α 1.0.1.1](https://github.com/Naruyoko/OmegaNum.js/commit/504e58eadf899b1add34b46aaa82e67eda54f929)

**Comment by Patashu** [comment]
Fixed!
