### ISSUE TITLE
Can't convert BigInt to OmegaNum without returning `NaN` or `Infinity`

### ISSUE THREAD

**Issue by James103** [Naruyoko/OmegaNum.js#37]
Currently (release 0.5.7), attempting to convert a BigInt value to OmegaNum will return either `NaN` if the BigInt is being passed in directly or `Infinity` if the BigInt (whose value is bigger than 2<sup>1024</sup>) is converted to a string which is then passed into the OmegaNum constructor.

```js
new OmegaNum(1234n).toString()
'NaN'

new OmegaNum(2n**1234n).toString()
'NaN'

new OmegaNum(String(1234n)).toString()
'1234'

new OmegaNum(String(2n**1234n)).toString()
'Infinity'
```

The expected output should be 1234 for the `1234n` test case and approximately 2.958112e371 for the `2n**1234n` test case.

**Comment by James103** [comment]
The test works as expected in all four cases in both `OmegaNum.js` and `ExpantaNum.js`.
Even a string solely consisting of a million `1` digits converts properly (up to precision limitations).

**Comment by jakub791** [comment]
But that has nothing to do with BigInt?

**Comment by James103** [comment]
For similar effect, I can construct a BigInt whose value is `9n ** 1048576n` and pass it into the OmegaNum (or ExpantaNum) constructor and it will still work and give the expected output (`6.216956799074759e1000595`).
